### ISSUE TITLE
AttributeErro

### ISSUE THREAD

**Issue by hello11151** [shenzudan/km-porn-spider#1]
"D:\Program Files\pythonProject4\Scripts\python.exe" E:/pycharm/km-porn-spider-master/main.py 
线程池最大线程数: 16
Traceback (most recent call last):
  File "E:\pycharm\km-porn-spider-master\main.py", line 98, in <module>
    page, curLen = run(model)
  File "E:\pycharm\km-porn-spider-master\main.py", line 57, in run
    data = km.getHot(page, 20)
  File "E:\pycharm\km-porn-spider-master\km.py", line 12, in getHot
    all = u.post(const.URL_HOT, {"page": page, "perPage": perPage})
  File "E:\pycharm\km-porn-spider-master\util.py", line 30, in post
    fd = getParam(json.dumps(data))
  File "E:\pycharm\km-porn-spider-master\util.py", line 16, in getParam
    data = aes.encrypt(json)
  File "E:\pycharm\km-porn-spider-master\AES.py", line 22, in encrypt
    cryptor = AES.new(self.key, self.mode, IV)
AttributeError: 'function' object has no attribute 'new'
您好，在运行main.py这个文件时，会出现AttributeError: 'function' object has no attribute 'new'这个问题，请问是什么原因呢，

**Comment by shenzudan** [comment]
python版本3.9
mac安装: pip install pycryptodome
win安装: pip install pycrypto
看看有无报错

**Comment by hello11151** [comment]
"D:\Program Files\km-porn-spider-master\Scripts\python.exe" E:/pycharm/km-porn-spider-master/util.py 
Traceback (most recent call last):
  File "E:\pycharm\km-porn-spider-master\util.py", line 4, in <module>
    import AES
  File "E:\pycharm\km-porn-spider-master\AES.py", line 1, in <module>
    from Crypto import AES
ImportError: cannot import name 'AES' from 'Crypto' (D:\Users\ADA\AppData\Local\Programs\Python\Python39\lib\site-packages\Crypto\__init__.py)
仍然是这个Crypto的问题，这个太难解了

**Comment by shenzudan** [comment]
我感觉你是没安装成功pycrypto,你看到包安装成功没
我在虚拟机上安装，首先出现缺少MS VC++ 14.0 缺失
下载visual-cpp-build-tools后安装

然后报io.h缺失
继续安装windows sdk 在visualstudio installer里单个组件可以找到

例如我的 安装后加到环境变量path编译
C:\Program Files (x86)\Windows Kits\10\Include\10.0.20348.0\ucrt

还有其他pycrypto安装问题看
https://www.cnblogs.com/simplezhuo/p/10286475.html

**Comment by shenzudan** [comment]
提交了dockerfile 生成了requirements 不行用docker吧

**Comment by hello11151** [comment]
我晚上再搏一搏

发自我的iPhone

**Comment by hello11151** [comment]
我将from Crypto import AES替换成from Crypto.Cipher import AES。最后运行main.py的时候，出现AttributeError: 'AES_ENCRYPT' object has no attribute 'key'。这应该是最后一关了，请大神指点

**Comment by hello11151** [comment]
会不会是哪里没有配置对

**Comment by shenzudan** [comment]
估计引入的就不该是这个包  不然你去百度搜aes的加密方案吧
我也不是很懂python
只是写起来比较方便就用了

**Comment by hello11151** [comment]
这几天不太舒服，过几天我再试一下，多谢

发自我的iPhone

**Comment by hello11151** [comment]
好消息呀，大神，代码终于跑起来了，我将".ylm"复制到SRC文件中，环境用的是打包环境，解决了问题，然后现在是我想下载呀，您说是配置哪个文件，我怎么找不到填地址的地方呢，需要在哪个文件调整，劳烦您指教一二

**Comment by hello11151** [comment]
已经显示采集成功，看不到视频在哪里，需要下载下来，才算最后的成功 (*^▽^*)

**Comment by shenzudan** [comment]
下载？太多了吧 地址已经有了 你看video_url 你直接写个函数保存到本地就好了 估计得oss挂载到服务器来下，百T级别吧

**Comment by shenzudan** [comment]
mv_play_url这个

**Comment by hello11151** [comment]
下载当日热门，当日更新就够，也就30个多个

发自我的iPhone

**Comment by shenzudan** [comment]
兄弟 注意身体

**Comment by hello11151** [comment]
谢谢，我虚的不行，我还没下载呢，咋样编辑这个函数呀，我不会python，我就觉得这软件真强大，想要啥都可以下载下来

发自我的iPhone

**Comment by shenzudan** [comment]
我看过两天有空我写下吧 哈哈哈 你是真行

**Comment by shenzudan** [comment]
你会前端的话可以搞个手机版无广告客户端出来 那岂不是更好

**Comment by hello11151** [comment]
有破解版，不要会员 ，还能缓存呢，手刷着累嘛不是，这软件是精品呀，都可以收藏(*￣︶￣)，唯一缺点就是有时候打开视频会很慢，人家都叫慢猫。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shenzudan/km-porn-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenzudan/km-porn-spider] AttributeErro (Issue #1)





 
你会前端的话可以搞个手机版无广告客户端出来 那岂不是更好

**Comment by hello11151** [comment]
19年的时候，网友推荐的这个软件，真的是国产精品呀，不过现在作品质量不太行，而且人工刷视频太耗时间了，然后在52破解上面，有人分析了一波这个软件，可以用Python批量采集，感觉不错，我就从下载py和pycharm开始，一点点网上查知识，学习安装，配置环境，就为了有朝一日攻克这玩意




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shenzudan/km-porn-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenzudan/km-porn-spider] AttributeErro (Issue #1)





 
我看过两天有空我写下吧 哈哈哈 你是真行

**Comment by hello11151** [comment]
您看我在Github上面关注的另外一个程序猿大神，他这个可能太就远了，还教怎么JS逆向呢，可惜没有学会，而且搞得我52破解的账号加了一次违规(*^▽^*)，https://github.com/zg10472580/Python_KuaiMao&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shenzudan/km-porn-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenzudan/km-porn-spider] AttributeErro (Issue #1)





 
你会前端的话可以搞个手机版无广告客户端出来 那岂不是更好

**Comment by shenzudan** [comment]
我是反编译了他们的apk拿的算法，他们后来才做的网页版，我看js里的秘钥一样，算法应该是一样的，我这个纯json，没那么多乱七八糟的后端渲染数据，已经采了40W视频了。写过一版java版的，不知道怎么请求就是不行，不能用了，我就用python重写了

**Comment by shenzudan** [comment]
速度还挺快的 现在人家的域名接入了cloudfare做加速 应该没那么卡了 反正拿地址 迅雷秒下

**Comment by hello11151** [comment]
人生苦短，要用Python




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shenzudan/km-porn-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 下午4:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenzudan/km-porn-spider] AttributeErro (Issue #1)





 
我是反编译了他们的apk拿的算法，他们后来才做的网页版，我看js里的秘钥一样，算法应该是一样的，我这个纯json，没那么多乱七八糟的后端渲染数据，已经采了40W视频了。写过一版java版的，不知道怎么请求就是不行，不能用了，我就用python重写了

**Comment by hello11151** [comment]
这个软件也好几年了，不知道还能坚持多久了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shenzudan/km-porn-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenzudan/km-porn-spider] AttributeErro (Issue #1)





 
速度还挺快的 现在人家的域名接入了cloudfare做加速 应该没那么卡了 反正拿地址 迅雷秒下

**Comment by hello11151** [comment]
软件上面每天更新，也没有数过，也就几十个视频就到底了，也就几个视频确实不错，可以下载。大部分视频没必要下载，就算缓存下来，我都删掉了，500G的硬盘 ，存了100多G差不多




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shenzudan/km-porn-spider"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shenzudan/km-porn-spider] AttributeErro (Issue #1)





 
速度还挺快的 现在人家的域名接入了cloudfare做加速 应该没那么卡了 反正拿地址 迅雷秒下

**Comment by hello11151** [comment]
哥，我又找到了一个地址，很遗憾，这个也是没有跑起来https://github.com/rabbit-yu/python-kuaimao

**Comment by shenzudan** [comment]
哈哈，我来写下下载，他这个直接引用js代码的aes 应该没问题的。

**Comment by shenzudan** [comment]
搞完了 试试吧

**Comment by hello11151** [comment]
大神呀～～～～我下班试，@_@

发自我的iPhone

**Comment by hello11151** [comment]
大神，成功了，感谢你的开源共享精神。多谢！

发自我的iPhone

**Comment by hello11151** [comment]
啊？大神你说啥，我没看懂

发自我的iPhone

**Comment by shenzudan** [comment]
> 啊？大神你说啥，我没看懂 发自我的iPhone
> […](#)
> 在 2022年9月13日，07:47，Stan ***@***.***> 写道： ﻿ Closed #1 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.

我把这个issue关了
